manifest: replace hardware/interfaces from Lineage
ERROR: files are incompatible: android.hardware.light@2.0::ILight/default is deprecated in compatibility matrix at FCM Version 5; it should not be served.
    because it matches android.hardware.light@2.0::ILight/default from /system/etc/vintf/compatibility_matrix.4.xml: Success

Signed-off-by: Edwiin Kusuma Jaya <kutemeikito0905@gmail.com>